FROM php:7.1.11-fpm-alpine
MAINTAINER Andre Shen 

# RUN docker-php-ext-install -j$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) \
# iconv gd mbstring fileinfo curl xmlreader xmlwriter spl ftp mysqli

# VOLUME /var/www/html
# RUN chown -R www-data:www-data /var/www/html
# RUN chmod -R g+w .
